### ISSUE TITLE
VULTR $2.5 is permanently sold-out ... so just a way to look cheaper then they are

### ISSUE THREAD

**Issue by sigio** [joedicastro/vps-comparison#27]
Since I've had credits in my vultr account, they haven't had the $2.5 package for sale... it's permanently sold-out. Yet they only tell this after you deposit money and try to order this, which is a bit crappy, since I was looking into getting those instances for some workshops.

So yeah... while they may advertise the $2.5 instances, you can't really ever get them (same with OVH and their $5 dedicated boxes, I have one, but can't ever get a second one, but at least they still become available for short times most weeks)

**Comment by joedicastro** [comment]
I understand you, I had also the same suspicions about this, in fact I even opened a support ticket asking about this topic. But being frankly my history with Vultr is different than yours.

I opened an account with them about half March of this year and I created, tested and destroyed several servers under this plan until one day (about three weeks later), when after destroying a server I could not longer create any more servers using this plan. The message that I got is the same as you I suppose, that the servers under this plan are "temporarily sold-out". 

After a lot of time waiting, I opened that ticket and they told me that they still offer this plan in the Miami and New Jersey locations, which is true, but they couldn't tell me when they would be able to offer again the same plan in European locations. 

The reasons behind this way of doing things are unknown by me, but as I say at the beginning I have doubts about the motivations to proceed like that.

About OVH and its dedicated servers I have no direct experience to share.

The common sense tell me also that this kind of plans are used also as bait to bring in new users, but then I don't understand how I was able to create so many servers under this plan for several weeks. Occam's razors suggest me that they only provision a few servers in each location until they are all sold-out but at the same time it's very strange that all of the locations (except two) are sold-out simultaneously at the same time. Something doesn't suit here.

**Comment by trr** [comment]
Their $2.50 plans are simply only available at a couple of their locations (eg Miami FL).

They could certainly do a better job of making this clearer from the start because currently the first you discover it is when you are some way into the sign-up process.  A small note where they advertise this plan saying "Only available at &lt;locations>" at minimum.

**Comment by sigio** [comment]
Yeah... i've ordered a few of them now... but they are only available in Miami ... and you are limited to 10 boxes.

**Comment by sigio** [comment]
Created a pull-request to clarify :)

**Comment by joedicastro** [comment]
Well, that's not exactly true, they are currently available both in Miami and New York. Also the 10 boxes limit is generic, not only to this plan (see it in General Features), you can request to extended it. I accepted your pull request anyway and them fixed it. Thanks!

**Comment by joedicastro** [comment]
@trr You're right on this, when I contacted with them about this they were very brief and without too much clarification about the future of the situation.

**Comment by spidernik84** [comment]
Discovered this now myself: it's still true for all European locations.
This is borderline fraud, to be honest. Definitely not the most transparent way to sell their services... I picked them exclusively for this price difference, else I would have gone with DigitalOcean.

**Comment by HashingTag** [comment]
What the fuck? [Vultr 2.5 dollar plan](http://gaden.ga/host) is gone for ages now. I was waiting for my cheap sweet lightning fast VPS in Singapore, those tricky bastards aren't fooling anyone, "**Temporarily Sold Out**" hahahahha like that's how their system works lol.

On the other hand, DigitalOcean delivers what it promises, no bullshit.

**Comment by sigio** [comment]
Yeah.... they should replace that text with 'only available in miami and <1 other place>' .... I've ordered those a couple of times, but always only in US, never in EU-zone.

**Comment by joshamore** [comment]
I just spun up a $2.5 instance. It's only available in Miami. 

Sure, they could be clearer about were it's available, but it's still **awesome** value.

**Comment by nothinghope** [comment]
but in vultr they  give $2.5 server with ipv6. this works for connect to server or anthoer bullshits.
and they charge $3 dedicated ip.
it is worth.
please reply

**Comment by winex01** [comment]
damn, i got same experience too, get click baited by those ads.

**Comment by anvodev** [comment]
damn, I got this issue too. Oh my $100 :(

**Comment by richpeck** [comment]
![untitled](https://user-images.githubusercontent.com/1104431/45203460-35997500-b274-11e8-836c-841c42c39462.png)

Amsterdam datacenter

**Comment by AurorahHarmony** [comment]
I have one of these VPS set up in Silicon Valley through them. Dunno why they stopped offering them to be quite honest.

**Comment by dhaveed** [comment]
For anyone checking as at September 2019, the $2.5/mo and $3.5/mo options are currently available in both Atlanta and New York (NJ) data centers. 😀

**Comment by ctrlshiftjv** [comment]
In case someone comes here like I did searching where to find Vultr's $2.5/mo and $3.5/mo plan in August 2020 it's only available in Atlanta and New York (NJ) data centers.

**Comment by exu-g** [comment]
As of March 2021 you can get the 2.5$/mo at New York and Atlanta locations. 3.5$/mo is only available in New York.  
This really should be made clear before asking users to create an account.

**Comment by benyanke** [comment]
Still only NY and Atlanta, and the $2.50/mo ones are Ipv6 only.

**Comment by RW21** [comment]
No $2.5/mo options as of Nov 9.

**Comment by StaudeKevin** [comment]
Still no $2.5/mo option for any location...

**Comment by elitan** [comment]
$2.5/mo available in Atlanta using Intel Regular Performance.

**Comment by ronaldaug** [comment]
Clickbait! It's only available for  locations in America and user with United State address. Lightsail $3.50 plan appears to be promising.

**Comment by elitan** [comment]
> Clickbait! It's only available for locations in America and user with United State address. Lightsail $3.50 plan appears to be promising.

I was able to use it with a Swedish address.

**Comment by Cyberes** [comment]
Sold out
