### ISSUE TITLE
Linode doesn't accept Paypal

### ISSUE THREAD

**Issue by peshmerge** [joedicastro/vps-comparison#29]
Hello, 

thanks for this amazing and handy comparison. Linode doesn't accept paypal payments.
They only accept " We accept Visa, MasterCard, American Express, and Discover" 

thanks.

**Comment by joedicastro** [comment]
You missed the "Note" of that table that explains that:

![captura el 2017-06-19 a las 20 24 04](https://user-images.githubusercontent.com/390964/27299812-ddaa3a86-552d-11e7-9ae6-1e1c6bcb52d8.png)

And here is your proof:

![captura el 2017-06-19 a las 20 20 32](https://user-images.githubusercontent.com/390964/27299948-4dc6c320-552e-11e7-9a56-2b37bdc46cb9.png)

Thanks anyway, for open the issue!

**Comment by peshmerge** [comment]
Ops :100:
