### ISSUE TITLE
Scaleway SMTP ports

### ISSUE THREAD

**Issue by petk** [joedicastro/vps-comparison#31]
Scaleway has blocked SMTP ports for their machines so they can protect other servers and you can enable those ports only by request and after sending personal IDs and/or company certificates. This might be an inconvenience for some users and it is not a common practice elsewhere. In most cases registrations are plain and simple, except for maybe also OVH where you need to provide them the bank details (and some other personal info at the registration step directly). Is this an info that might be worth noting somewhere in this repository also?

P.S: great comparison of these VPS offers - I found it very useful - what to choose and what not to... :100:

**Comment by joedicastro** [comment]
Thanks for the tip, I'll look into that and add it to the comparison.

**Comment by petk** [comment]
Update: Scaleway now has simplified and working enabling of [SMTP ports](https://www.scaleway.com/faq/servers/network/#-I-cannot-send-any-email)

**Comment by frostbtn** [comment]
They still require your ID and a photo with you holding this ID to enable that switch though.

**Comment by petk** [comment]
Hm, I see...
