### ISSUE TITLE
Correct a statement about Scaleway instances limits

### ISSUE THREAD

**Issue by RaitoBezarius** [joedicastro/vps-comparison#6]
You said that:

> The default limits usually can be increased by asking support. Those limits are set by default by the providers to stop abusing the accounts.

But, in fact, it's not true for Scaleway, you have to pay a higher level of support to get higher limits.

**Comment by joedicastro** [comment]
I'll look into that, I think that I read it like that in the provider's documentation, but if you know it first hand, let me know.

**Comment by RaitoBezarius** [comment]
Well, I contacted their support to increase my limits and got the generic answer (which is increase your service level even though you don't need "support", e.g. http://screencloud.net/v/BWJg1)

Their FAQ mentions it also: https://www.scaleway.com/faq/general/#-Is-there-limits-on-the-number-of-resources-I-can-have

**Comment by joedicastro** [comment]
Thanks for share that! 

Well, I read about that in some place, all of his way of doing things is very confusing. In the same FAQ they open a door for exceptions¹ in particular cases, asking support, but now I see that they didn't even ask you why. I'll fix this.

¹ - See the image. That "outside of this scheme" is a little ambiguous. 

![2017-05-03-214510_960x1183_scrot](https://cloud.githubusercontent.com/assets/390964/25678445/0be02d4c-304a-11e7-86a6-526245cee379.png)
